### ISSUE TITLE
Feature request: "input inversion" mode

### ISSUE THREAD

**Issue by kmgteano** [x-sheep/puzzles#2]
Another "this is great on the Android port and would be lovely to have on Windows" feature, particularly for touch-enabled Windows devices: a button to swap the behavior of left click and right click/long press. 

For example, in Mines, clicking this button would make left-click put down a flag and right-click/long press attempt to clear the tile. 

This would mean you could play a game using a stylus and only single presses, by alternating modes with the button.

**Comment by x-sheep** [comment]
Hi,

The button in the bottom left switches the left- and right click actions. On Mines, it is labeled "Flag".
