### ISSUE TITLE
Dominosa: VK_NUMPAD keys are not mapped to digits

### ISSUE THREAD

**Issue by rillig** [x-sheep/puzzles#3]
When I press VK_NUMPAD_4, nothing happens. No matter whether NumLock is enabled or not.

VK_NUMPAD_4 should do the same as VK_4.

**Comment by x-sheep** [comment]
In the latest UWP release the numpad always inputs a number, regardless of Num Lock being enabled or not. This mirrors the behaviour of the official Windows port.
