### ISSUE TITLE
Dominosa: corners of rounded rectangles are blurry

### ISSUE THREAD

**Issue by rillig** [x-sheep/puzzles#4]
![image](https://user-images.githubusercontent.com/3233724/67892003-0e76c480-fb54-11e9-8718-ab80d7522578.png)

The rounded corners of the black area should not be larger than the rectangle itself. Currently they are.

**Comment by eekee** [comment]
Magnets has the same issue.

**Comment by eekee** [comment]
The same issue is visible in the Android version. It's less noticeable, perhaps due to the small pixel size.  I can see it on my tablet when I look closely. 

I don't see it on the Javascript or Win32 versions.

**Comment by x-sheep** [comment]
This is fixed in 61cd684814df1a4ba2bd1455d2fd3a127b6d69ce and will be included in the next release.
